"""migrate_to_jsonb

Revision ID: 649aac93f9c1
Revises: 0001_initial
Create Date: 2026-01-28 16:40:43.821173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '649aac93f9c1'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'recommendations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'risks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'fit_for',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', name='cardstatus'),
               nullable=True)
    op.alter_column('questions', 'requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('questions', 'status',
               existing_type=postgresql.ENUM('OPEN', 'COMPILING_SUMMARY', 'RESOLVED', name='questionstatus'),
               nullable=True)
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('OPEN', 'REVIEWED', 'REJECTED', name='reportstatus'),
               nullable=True)
    op.alter_column('user_profiles', 'cities_of_experience',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('user_profiles', 'cities_of_experience',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('OPEN', 'REVIEWED', 'REJECTED', name='reportstatus'),
               nullable=False)
    op.alter_column('questions', 'status',
               existing_type=postgresql.ENUM('OPEN', 'COMPILING_SUMMARY', 'RESOLVED', name='questionstatus'),
               nullable=False)
    op.alter_column('questions', 'requirements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', name='cardstatus'),
               nullable=False)
    op.alter_column('cards', 'fit_for',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'risks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cards', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
